"""Add ring and ring_color fields to User model

Revision ID: 0cad63af81ed
Revises: 7de01cee5ee7
Create Date: 2025-09-21 08:16:21.582603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cad63af81ed'
down_revision = '7de01cee5ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ring', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ring_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ring_color')
        batch_op.drop_column('ring')

    # ### end Alembic commands ###
