"""Add bio field to User model

Revision ID: 199e66927256
Revises: 0cad63af81ed
Create Date: 2025-09-21 08:24:40.695755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199e66927256'
down_revision = '0cad63af81ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.drop_column('ring_color')
        batch_op.drop_column('ring')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ring', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ring_color', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
