"""Add social media and custom website fields to User model

Revision ID: 2424f22ec303
Revises: 199e66927256
Create Date: 2025-09-24 07:09:51.982249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2424f22ec303'
down_revision = '199e66927256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))

    with op.batch_alter_table('community_post', schema=None) as batch_op:
        batch_op.alter_column('post_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'public'::character varying"))

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_column('short_name')

    with op.batch_alter_table('schedule_subject_pref', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('schedule_subject_pref_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('twitter_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('youtube_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('custom_website_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('custom_website_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('custom_website_name')
        batch_op.drop_column('custom_website_url')
        batch_op.drop_column('youtube_url')
        batch_op.drop_column('twitter_url')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('github_url')

    with op.batch_alter_table('schedule_subject_pref', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('schedule_subject_pref_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    with op.batch_alter_table('community_post', schema=None) as batch_op:
        batch_op.alter_column('post_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'public'::character varying"))

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_column('weight')
        batch_op.drop_column('max_score')
        batch_op.drop_column('score')

    # ### end Alembic commands ###
