"""Update social media fields to use usernames instead of URLs

Revision ID: 9e67ebb5282b
Revises: 2424f22ec303
Create Date: 2025-09-24 07:20:31.720786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e67ebb5282b'
down_revision = '2424f22ec303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('instagram_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('twitter_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('youtube_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('linkedin_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tiktok_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('discord_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('custom_links', sa.Text(), nullable=True))
        batch_op.drop_column('github_url')
        batch_op.drop_column('custom_website_name')
        batch_op.drop_column('youtube_url')
        batch_op.drop_column('custom_website_url')
        batch_op.drop_column('twitter_url')
        batch_op.drop_column('instagram_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instagram_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('twitter_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('custom_website_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('youtube_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('custom_website_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('custom_links')
        batch_op.drop_column('discord_username')
        batch_op.drop_column('tiktok_username')
        batch_op.drop_column('linkedin_username')
        batch_op.drop_column('youtube_username')
        batch_op.drop_column('twitter_username')
        batch_op.drop_column('instagram_username')
        batch_op.drop_column('github_username')

    # ### end Alembic commands ###
