"""Add custom website fields to User model

Revision ID: ab29fec1042b
Revises: cc73eaa47526
Create Date: 2025-09-24 07:29:17.475887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab29fec1042b'
down_revision = 'cc73eaa47526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_website_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('custom_website_name', sa.String(length=100), nullable=True))
        batch_op.drop_column('custom_links')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_links', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('custom_website_name')
        batch_op.drop_column('custom_website_url')

    # ### end Alembic commands ###
