"""Add show_email field to User model

Revision ID: cc73eaa47526
Revises: 9e67ebb5282b
Create Date: 2025-09-24 07:24:07.742863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc73eaa47526'
down_revision = '9e67ebb5282b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_email', sa.Boolean(), nullable=True))
    
    # Update existing records to have show_email = False
    op.execute("UPDATE \"user\" SET show_email = false WHERE show_email IS NULL")
    
    # Now make the column NOT NULL
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('show_email', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('show_email')

    # ### end Alembic commands ###
