"""Add email change verification and school fields

Revision ID: f2bc06494590
Revises: 63d9b3da5614
Create Date: 2025-09-19 13:55:38.470473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2bc06494590'
down_revision = '63d9b3da5614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('email_change_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('school_university', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('school_university')
        batch_op.drop_column('email_change_token')
        batch_op.drop_column('pending_email')

    # ### end Alembic commands ###
